# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/marc/Marc's Market Maker"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/marc/Marc's Market Maker/build"

# Include any dependencies generated for this target.
include CMakeFiles/lob_engine.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/lob_engine.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/lob_engine.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/lob_engine.dir/flags.make

CMakeFiles/lob_engine.dir/codegen:
.PHONY : CMakeFiles/lob_engine.dir/codegen

CMakeFiles/lob_engine.dir/engine/lob.cpp.o: CMakeFiles/lob_engine.dir/flags.make
CMakeFiles/lob_engine.dir/engine/lob.cpp.o: /Users/marc/Marc's\ Market\ Maker/engine/lob.cpp
CMakeFiles/lob_engine.dir/engine/lob.cpp.o: CMakeFiles/lob_engine.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir="/Users/marc/Marc's Market Maker/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/lob_engine.dir/engine/lob.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/lob_engine.dir/engine/lob.cpp.o -MF CMakeFiles/lob_engine.dir/engine/lob.cpp.o.d -o CMakeFiles/lob_engine.dir/engine/lob.cpp.o -c "/Users/marc/Marc's Market Maker/engine/lob.cpp"

CMakeFiles/lob_engine.dir/engine/lob.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/lob_engine.dir/engine/lob.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/Users/marc/Marc's Market Maker/engine/lob.cpp" > CMakeFiles/lob_engine.dir/engine/lob.cpp.i

CMakeFiles/lob_engine.dir/engine/lob.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/lob_engine.dir/engine/lob.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/Users/marc/Marc's Market Maker/engine/lob.cpp" -o CMakeFiles/lob_engine.dir/engine/lob.cpp.s

CMakeFiles/lob_engine.dir/engine/bindings.cpp.o: CMakeFiles/lob_engine.dir/flags.make
CMakeFiles/lob_engine.dir/engine/bindings.cpp.o: /Users/marc/Marc's\ Market\ Maker/engine/bindings.cpp
CMakeFiles/lob_engine.dir/engine/bindings.cpp.o: CMakeFiles/lob_engine.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir="/Users/marc/Marc's Market Maker/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/lob_engine.dir/engine/bindings.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/lob_engine.dir/engine/bindings.cpp.o -MF CMakeFiles/lob_engine.dir/engine/bindings.cpp.o.d -o CMakeFiles/lob_engine.dir/engine/bindings.cpp.o -c "/Users/marc/Marc's Market Maker/engine/bindings.cpp"

CMakeFiles/lob_engine.dir/engine/bindings.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/lob_engine.dir/engine/bindings.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/Users/marc/Marc's Market Maker/engine/bindings.cpp" > CMakeFiles/lob_engine.dir/engine/bindings.cpp.i

CMakeFiles/lob_engine.dir/engine/bindings.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/lob_engine.dir/engine/bindings.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/Users/marc/Marc's Market Maker/engine/bindings.cpp" -o CMakeFiles/lob_engine.dir/engine/bindings.cpp.s

# Object files for target lob_engine
lob_engine_OBJECTS = \
"CMakeFiles/lob_engine.dir/engine/lob.cpp.o" \
"CMakeFiles/lob_engine.dir/engine/bindings.cpp.o"

# External object files for target lob_engine
lob_engine_EXTERNAL_OBJECTS =

lob_engine.cpython-39-darwin.so: CMakeFiles/lob_engine.dir/engine/lob.cpp.o
lob_engine.cpython-39-darwin.so: CMakeFiles/lob_engine.dir/engine/bindings.cpp.o
lob_engine.cpython-39-darwin.so: CMakeFiles/lob_engine.dir/build.make
lob_engine.cpython-39-darwin.so: CMakeFiles/lob_engine.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir="/Users/marc/Marc's Market Maker/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Linking CXX shared module lob_engine.cpython-39-darwin.so"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/lob_engine.dir/link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/lob_engine.dir/build: lob_engine.cpython-39-darwin.so
.PHONY : CMakeFiles/lob_engine.dir/build

CMakeFiles/lob_engine.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/lob_engine.dir/cmake_clean.cmake
.PHONY : CMakeFiles/lob_engine.dir/clean

CMakeFiles/lob_engine.dir/depend:
	cd "/Users/marc/Marc's Market Maker/build" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/Users/marc/Marc's Market Maker" "/Users/marc/Marc's Market Maker" "/Users/marc/Marc's Market Maker/build" "/Users/marc/Marc's Market Maker/build" "/Users/marc/Marc's Market Maker/build/CMakeFiles/lob_engine.dir/DependInfo.cmake" "--color=$(COLOR)" lob_engine
.PHONY : CMakeFiles/lob_engine.dir/depend

