# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# compile CXX with /usr/bin/c++
CXX_DEFINES = -Dlob_engine_EXPORTS

CXX_INCLUDES = -I"/Users/marc/Marc's Market Maker/engine" -isystem /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -isystem /Users/marc/Library/Python/3.9/lib/python/site-packages/pybind11/include

CXX_FLAGSarm64 = -O3 -march=native -DNDEBUG -std=c++17 -arch arm64 -fPIC -fvisibility=hidden

CXX_FLAGS = -O3 -march=native -DNDEBUG -std=c++17 -arch arm64 -fPIC -fvisibility=hidden

