# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/marc/Marc's Market Maker"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/marc/Marc's Market Maker/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/homebrew/bin/ctest $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"gmock\" \"gtest\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/marc/Marc's Market Maker/build/CMakeFiles" "/Users/marc/Marc's Market Maker/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/marc/Marc's Market Maker/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lob_engine

# Build rule for target.
lob_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lob_engine
.PHONY : lob_engine

# fast build rule for target.
lob_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/build
.PHONY : lob_engine/fast

#=============================================================================
# Target rules for targets named lob_benchmark

# Build rule for target.
lob_benchmark: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lob_benchmark
.PHONY : lob_benchmark

# fast build rule for target.
lob_benchmark/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/build
.PHONY : lob_benchmark/fast

#=============================================================================
# Target rules for targets named test_engine

# Build rule for target.
test_engine: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_engine
.PHONY : test_engine

# fast build rule for target.
test_engine/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/build
.PHONY : test_engine/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

engine/benchmark.o: engine/benchmark.cpp.o
.PHONY : engine/benchmark.o

# target to build an object file
engine/benchmark.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/engine/benchmark.cpp.o
.PHONY : engine/benchmark.cpp.o

engine/benchmark.i: engine/benchmark.cpp.i
.PHONY : engine/benchmark.i

# target to preprocess a source file
engine/benchmark.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/engine/benchmark.cpp.i
.PHONY : engine/benchmark.cpp.i

engine/benchmark.s: engine/benchmark.cpp.s
.PHONY : engine/benchmark.s

# target to generate assembly for a file
engine/benchmark.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/engine/benchmark.cpp.s
.PHONY : engine/benchmark.cpp.s

engine/bindings.o: engine/bindings.cpp.o
.PHONY : engine/bindings.o

# target to build an object file
engine/bindings.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/engine/bindings.cpp.o
.PHONY : engine/bindings.cpp.o

engine/bindings.i: engine/bindings.cpp.i
.PHONY : engine/bindings.i

# target to preprocess a source file
engine/bindings.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/engine/bindings.cpp.i
.PHONY : engine/bindings.cpp.i

engine/bindings.s: engine/bindings.cpp.s
.PHONY : engine/bindings.s

# target to generate assembly for a file
engine/bindings.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/engine/bindings.cpp.s
.PHONY : engine/bindings.cpp.s

engine/lob.o: engine/lob.cpp.o
.PHONY : engine/lob.o

# target to build an object file
engine/lob.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/engine/lob.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/engine/lob.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/engine/lob.cpp.o
.PHONY : engine/lob.cpp.o

engine/lob.i: engine/lob.cpp.i
.PHONY : engine/lob.i

# target to preprocess a source file
engine/lob.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/engine/lob.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/engine/lob.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/engine/lob.cpp.i
.PHONY : engine/lob.cpp.i

engine/lob.s: engine/lob.cpp.s
.PHONY : engine/lob.s

# target to generate assembly for a file
engine/lob.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_engine.dir/build.make CMakeFiles/lob_engine.dir/engine/lob.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lob_benchmark.dir/build.make CMakeFiles/lob_benchmark.dir/engine/lob.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/engine/lob.cpp.s
.PHONY : engine/lob.cpp.s

tests/test_engine.o: tests/test_engine.cpp.o
.PHONY : tests/test_engine.o

# target to build an object file
tests/test_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/tests/test_engine.cpp.o
.PHONY : tests/test_engine.cpp.o

tests/test_engine.i: tests/test_engine.cpp.i
.PHONY : tests/test_engine.i

# target to preprocess a source file
tests/test_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/tests/test_engine.cpp.i
.PHONY : tests/test_engine.cpp.i

tests/test_engine.s: tests/test_engine.cpp.s
.PHONY : tests/test_engine.s

# target to generate assembly for a file
tests/test_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine.dir/build.make CMakeFiles/test_engine.dir/tests/test_engine.cpp.s
.PHONY : tests/test_engine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... lob_benchmark"
	@echo "... lob_engine"
	@echo "... test_engine"
	@echo "... engine/benchmark.o"
	@echo "... engine/benchmark.i"
	@echo "... engine/benchmark.s"
	@echo "... engine/bindings.o"
	@echo "... engine/bindings.i"
	@echo "... engine/bindings.s"
	@echo "... engine/lob.o"
	@echo "... engine/lob.i"
	@echo "... engine/lob.s"
	@echo "... tests/test_engine.o"
	@echo "... tests/test_engine.i"
	@echo "... tests/test_engine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

