# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/marc/Marc's Market Maker"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/marc/Marc's Market Maker/build"

# Include any dependencies generated for this target.
include CMakeFiles/test_engine.dir/depend.make
# Include any dependencies generated by the compiler for this target.
include CMakeFiles/test_engine.dir/compiler_depend.make

# Include the progress variables for this target.
include CMakeFiles/test_engine.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/test_engine.dir/flags.make

CMakeFiles/test_engine.dir/codegen:
.PHONY : CMakeFiles/test_engine.dir/codegen

CMakeFiles/test_engine.dir/tests/test_engine.cpp.o: CMakeFiles/test_engine.dir/flags.make
CMakeFiles/test_engine.dir/tests/test_engine.cpp.o: /Users/marc/Marc's\ Market\ Maker/tests/test_engine.cpp
CMakeFiles/test_engine.dir/tests/test_engine.cpp.o: CMakeFiles/test_engine.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir="/Users/marc/Marc's Market Maker/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_1) "Building CXX object CMakeFiles/test_engine.dir/tests/test_engine.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/test_engine.dir/tests/test_engine.cpp.o -MF CMakeFiles/test_engine.dir/tests/test_engine.cpp.o.d -o CMakeFiles/test_engine.dir/tests/test_engine.cpp.o -c "/Users/marc/Marc's Market Maker/tests/test_engine.cpp"

CMakeFiles/test_engine.dir/tests/test_engine.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/test_engine.dir/tests/test_engine.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/Users/marc/Marc's Market Maker/tests/test_engine.cpp" > CMakeFiles/test_engine.dir/tests/test_engine.cpp.i

CMakeFiles/test_engine.dir/tests/test_engine.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/test_engine.dir/tests/test_engine.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/Users/marc/Marc's Market Maker/tests/test_engine.cpp" -o CMakeFiles/test_engine.dir/tests/test_engine.cpp.s

CMakeFiles/test_engine.dir/engine/lob.cpp.o: CMakeFiles/test_engine.dir/flags.make
CMakeFiles/test_engine.dir/engine/lob.cpp.o: /Users/marc/Marc's\ Market\ Maker/engine/lob.cpp
CMakeFiles/test_engine.dir/engine/lob.cpp.o: CMakeFiles/test_engine.dir/compiler_depend.ts
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --progress-dir="/Users/marc/Marc's Market Maker/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_2) "Building CXX object CMakeFiles/test_engine.dir/engine/lob.cpp.o"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -MD -MT CMakeFiles/test_engine.dir/engine/lob.cpp.o -MF CMakeFiles/test_engine.dir/engine/lob.cpp.o.d -o CMakeFiles/test_engine.dir/engine/lob.cpp.o -c "/Users/marc/Marc's Market Maker/engine/lob.cpp"

CMakeFiles/test_engine.dir/engine/lob.cpp.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Preprocessing CXX source to CMakeFiles/test_engine.dir/engine/lob.cpp.i"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -E "/Users/marc/Marc's Market Maker/engine/lob.cpp" > CMakeFiles/test_engine.dir/engine/lob.cpp.i

CMakeFiles/test_engine.dir/engine/lob.cpp.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green "Compiling CXX source to assembly CMakeFiles/test_engine.dir/engine/lob.cpp.s"
	/usr/bin/c++ $(CXX_DEFINES) $(CXX_INCLUDES) $(CXX_FLAGS) -S "/Users/marc/Marc's Market Maker/engine/lob.cpp" -o CMakeFiles/test_engine.dir/engine/lob.cpp.s

# Object files for target test_engine
test_engine_OBJECTS = \
"CMakeFiles/test_engine.dir/tests/test_engine.cpp.o" \
"CMakeFiles/test_engine.dir/engine/lob.cpp.o"

# External object files for target test_engine
test_engine_EXTERNAL_OBJECTS =

test_engine: CMakeFiles/test_engine.dir/tests/test_engine.cpp.o
test_engine: CMakeFiles/test_engine.dir/engine/lob.cpp.o
test_engine: CMakeFiles/test_engine.dir/build.make
test_engine: lib/libgtest_main.a
test_engine: lib/libgtest.a
test_engine: CMakeFiles/test_engine.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --green --bold --progress-dir="/Users/marc/Marc's Market Maker/build/CMakeFiles" --progress-num=$(CMAKE_PROGRESS_3) "Linking CXX executable test_engine"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles/test_engine.dir/link.txt --verbose=$(VERBOSE)
	/opt/homebrew/bin/cmake -D TEST_TARGET=test_engine -D "TEST_EXECUTABLE=/Users/marc/Marc's Market Maker/build/test_engine" -D TEST_EXECUTOR= -D "TEST_WORKING_DIR=/Users/marc/Marc's Market Maker/build" -D TEST_EXTRA_ARGS= -D TEST_PROPERTIES= -D TEST_PREFIX= -D TEST_SUFFIX= -D TEST_FILTER= -D NO_PRETTY_TYPES=FALSE -D NO_PRETTY_VALUES=FALSE -D TEST_LIST=test_engine_TESTS -D "CTEST_FILE=/Users/marc/Marc's Market Maker/build/test_engine[1]_tests.cmake" -D TEST_DISCOVERY_TIMEOUT=5 -D TEST_DISCOVERY_EXTRA_ARGS= -D TEST_XML_OUTPUT_DIR= -P /opt/homebrew/share/cmake/Modules/GoogleTestAddTests.cmake

# Rule to build all files generated by this target.
CMakeFiles/test_engine.dir/build: test_engine
.PHONY : CMakeFiles/test_engine.dir/build

CMakeFiles/test_engine.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles/test_engine.dir/cmake_clean.cmake
.PHONY : CMakeFiles/test_engine.dir/clean

CMakeFiles/test_engine.dir/depend:
	cd "/Users/marc/Marc's Market Maker/build" && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" "/Users/marc/Marc's Market Maker" "/Users/marc/Marc's Market Maker" "/Users/marc/Marc's Market Maker/build" "/Users/marc/Marc's Market Maker/build" "/Users/marc/Marc's Market Maker/build/CMakeFiles/test_engine.dir/DependInfo.cmake" "--color=$(COLOR)" test_engine
.PHONY : CMakeFiles/test_engine.dir/depend

